mlops accident k3s: step 3-26

diff --git a/k8s/base/jobs/airflow-init.yaml b/k8s/base/jobs/airflow-init.yaml
--- a/k8s/base/jobs/airflow-init.yaml
+++ b/k8s/base/jobs/airflow-init.yaml
@@ -12,28 +12,12 @@ spec:
     spec:
       # Comme dans le deployment de mlflow pour s'assurer des droits identiques partout
       securityContext:
-        runAsUser: 1000
-        runAsGroup: 1000
-        fsGroup: 1000
+        runAsUser: 0
+        #runAsUser: 5000
+        #runAsGroup: 5000
+        #fsGroup: 5000
 
       restartPolicy: OnFailure
-
-      initContainers:
-        # On ne met pas -U airflow dans le until car il n'est pas encore créé
-        # C'est justement le init-job qui le crée
-        - name: wait-for-postgres
-          image: postgres:16.13-trixie
-          imagePullPolicy: IfNotPresent
-
-          command:
-            - sh
-            - -c
-            - |
-              until pg_isready -h postgres -p 5432; do
-                echo "⏳ Waiting for postgres..."
-                sleep 2
-              done
-              echo "✅ Postgres is ready"
 
       containers:
         - name: airflow-init
@@ -49,25 +33,44 @@ spec:
             # Ainsi, bash -c reçoit cette chaine et bash l’interprète comme du code
             - |
               # Le script s'arrête si erreur
-              set -e
+              #set -e
+              #echo "📦 Installing missing providers..."
+              #pip install apache-airflow-providers-celery apache-airflow-providers-cncf-kubernetes
 
               echo "⚙️ Running Airflow migrations..."
-              airflow db migrate
+              airflow db migrate || echo "Migration failed, check logs"
 
               echo "🚀 Creating admin user (if not exists)..."
+              # On continue même si l'user existe déjà
+              airflow users create \
+                --username "$_AIRFLOW_WWW_USER_USERNAME" \
+                --password "$_AIRFLOW_WWW_USER_PASSWORD" \
+                --firstname Admin \
+                --lastname User \
+                --role Admin \
+                --email admin@example.com
               # Cherche si l'utilisateur (w: match uniquement le mot exact) existe déjà dans la liste
-              if ! airflow users list | grep -qw "$_AIRFLOW_WWW_USER_USERNAME"; then
-                airflow users create \
-                  --username "$_AIRFLOW_WWW_USER_USERNAME" \
-                  --password "$_AIRFLOW_WWW_USER_PASSWORD" \
-                  --firstname Admin \
-                  --lastname User \
-                  --role Admin \
-                  --email admin@example.com
-              else
-                echo "User already exists"
-              fi
+              #if ! airflow users list | grep -qw "$_AIRFLOW_WWW_USER_USERNAME"; then
+              #  airflow users create \
+              #    --username "$_AIRFLOW_WWW_USER_USERNAME" \
+              #    --password "$_AIRFLOW_WWW_USER_PASSWORD" \
+              #    --firstname Admin \
+              #    --lastname User \
+              #    --role Admin \
+              #    --email admin@example.com
+              #else
+              #  echo "User already exists"
+              #fi
               echo "✅ Airflow init completed"
+
+          #env:
+          #  - name: AIRFLOW_HOME
+          #    value: /app
+          #  - name: AIRFLOW__CORE__BASE_LOG_FOLDER
+          #    value: /app/logs
+          #  # On force aussi l'emplacement du fichier de configuration
+          #  - name: AIRFLOW_CONFIG
+          #    value: /app/airflow.cfg
 
           envFrom:
             - configMapRef:
